name: prog2
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
<<<<<<< HEAD
dependencies: {csv: ^5.0.1, xml: ^6.1.0}
=======
dependencies: {csv: ^5.0.1, grizzly_io: ^3.0.1}
>>>>>>> 00d82a640d49cb44564548996d9825c877332e77
